import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import styles from '../styles/Home.module.css';

export default function Home() {
  const router = useRouter();

  console.log(router);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/" locale="fr">
          <a className={styles.card}>FR</a>
        </Link>

        <Link href="/" locale="en">
          <a className={styles.card}>EN</a>
        </Link>
      </main>
    </div>
  );
}
